[package]
name = "solder"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
iced = { version = "0.14.0", features = ["canvas", "tokio"] }
pipewire = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
